# 파이썬입문 겨울방학 특강 (3)

### import 

In [1]:
import numpy as np

### numpy공부 1단계(복습)

`-` 넘파이의 위력 

In [2]:
l=[1,2,3]
a=np.array(l) ## list()

`-` 사칙연산 브로드캐스팅 

In [8]:
a+1

array([2, 3, 4])

In [9]:
l+1

TypeError: can only concatenate list (not "int") to list

In [10]:
a*2

array([2, 4, 6])

In [11]:
l*2

[1, 2, 3, 1, 2, 3]

In [12]:
a-2

array([-1,  0,  1])

In [13]:
l-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [14]:
a/2

array([0.5, 1. , 1.5])

In [15]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 기타수학연산가능 

In [18]:
np.sqrt(a), np.sqrt(l)

(array([1.        , 1.41421356, 1.73205081]),
 array([1.        , 1.41421356, 1.73205081]))

In [19]:
np.log(a), np.log(l)

(array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.69314718, 1.09861229]))

### numpy공부 2단계 

`-` 아래의 연립방정식 고려 

$\begin{cases}
x + y = 2 \\
y + z = 2 \\ 
x + z = 2 
\end{cases}$

`-` 행렬표현은? 

$\begin{bmatrix}
1 &1& 0 \\ 
0 & 1 & 1 \\
1 & 0 & 1 
\end{bmatrix} 
\begin{bmatrix}
x \\
y \\
z 
\end{bmatrix}
=
\begin{bmatrix}
2 \\
2 \\
2 
\end{bmatrix}
$

In [20]:
A = [[1,1,0],[0,1,1],[1,0,1]] 
A

[[1, 1, 0], [0, 1, 1], [1, 0, 1]]

In [22]:
A2=np.array(A)
A2

array([[1, 1, 0],
       [0, 1, 1],
       [1, 0, 1]])

`-` 